version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      docker: 18
  pre_build: 
    commands: 
      - echo PWD - $(pwd)
      - echo commit hash - $(git rev-parse HEAD)
      - echo ls - $(ls)
  build: 
    commands:
      - echo Build started on `date`
      - echo Running Tests...
      - make test
      - docker-compose build
      # need to override frontend build because docker-compose uses dev.Dockerfile
      - docker image build -t briand787b/piqlit-vue-frontend:$(git rev-parse HEAD) ./frontend/web/vue
  post_build: 
    commands:
      # put in command to NOT run post_build commands if build command fails
      - docker login -u briand787b -p $DOCKER_HUB_PASSWORD
      - docker image push briand787b/piqlit-vue-frontend:$(git rev-parse HEAD)
      - docker image tag piqlit_backend briand787b/piqlit-go-backend:$(git rev-parse HEAD)
      - docker image push briand787b/piqlit-go-backend:$(git rev-parse HEAD)
      - docker image tag piqlit_db briand787b/piqlit-pg-db:$(git rev-parse HEAD)
      - docker image push briand787b/piqlit-pg-db:$(git rev-parse HEAD)
      - echo Build completed on `date` 