version: "3.7"

services:
  backend:
    command: [ "/root/app", "--port", "8000", "--data", "/var/piqlit" ]
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./filesys/backend
        target: /var/piqlit