version: "3.7"

services:
  backend-master-api:
    build:
      context: ./backend
      dockerfile: ./api/Dockerfile
    image: "briand787b/piqlit-backend-api:latest"
    command: [
      "/root/app",
      "--port",
      "8080",
      "--master"
    ]
    ports:
      - "${MASTER_PORT:-8080}:8080" 
    environment:
      ENV: ${ENV:-default-from-compose}
  backend-slave-api-1:
    image: "briand787b/piqlit-backend-api:latest"
    command: [
      "/root/app",
      "--port",
      "8080"
    ]
    ports:
      - "${SLAVE_PORT_1:-8081}:8080"
  backend-slave-api-2:
    image: "briand787b/piqlit-backend-api:latest"
    command: [
      "/root/app",
      "--port",
      "8080"
    ]
    ports:
      - "${SLAVE_PORT_2:-8082}:8080"
