version: "3.7"

services:
  backend-master-api:
    build:
      context: ./backend
      dockerfile: ./api/rest/Dockerfile
    command: ["/root/app", "--port", "8080", "--master"]
    ports:
      - "${MASTER_PORT:-8080}:8080" 
    environment:
      ENV: ${ENV:-default-from-compose}
    networks:
      - public
      - private
  db:
    build:
      context: ./backend/core/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER:  ${POSTGRES_USER:-pl}
      POSTGRES_PASSWORD: ${POSRGRES_PASSWORD:-pl}
    ports:
      - "2345:5432"
    networks:
      - private
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-pl}", "-d", "${POSTGRES_USER:-pl}"] 
      interval: 10s 
      timeout: 5s 
      retries: 5
 
networks:
  public:
    driver: bridge
  private:
    driver: bridge
    