version: '3.7 '

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./api/rest/Dockerfile
    command: [ "/root/app", "--port", "8000", "--data", "/var/piqlit" ]
    ports:
      - 8000:8000
    environment:
      ENV: ${ENV:-default-from-compose}
      PL_DATABASE_HOST: "${PL_DATABASE_HOST:-db}"
      PL_DATABASE_NAME: "${PL_DATABASE_NAME:-pl}"
      PL_DATABASE_USER: "${PL_DATABASE_USER:-pl}"
      PL_DATABASE_PASS: "${PL_DATABASE_PASS:-pl}"
      PL_DATABASE_PORT: "${PL_DATABASE_PORT:-5432}"
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    build:
      context: ./backend/core/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER:  ${POSTGRES_USER:-pl}
      POSTGRES_PASSWORD: ${POSRGRES_PASSWORD:-pl}
    ports:
      - 2345:5432
    networks:
      - private
    restart: unless-stopped
    healthcheck: 
      test: [
        "CMD", 
        "pg_isready", 
        "-U", 
        "${POSTGRES_USER:-pl}", 
        "-d", 
        "${POSTGRES_USER:-pl}"
      ] 
      interval: 10s 
      timeout: 5s 
      retries: 5
 
networks:
  public:
    driver: bridge
  private:
    driver: bridge