version: "3.7"

services:
  backend:
    command: [ "/root/app", "--port", "8080", "--data", "/var/piqlit" ]
    volumes:
      - type: bind
        source: ./filesys/backend
        target: /var/piqlit