version: '3.7'

services:
  frontend-web-vue:
    build:
      context: ./frontend/web/vue
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      VUE_APP_BACKEND_HOST: ${VUE_BACKEND_HOST:-localhost:8000}
    volumes:
      - type: bind
        source: ./frontend/web/vue
        target: /app
  backend:
    volumes:
      - type: bind
        source: ./filesys/backend/dev
        target: /var/piqlit/media
  db:
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:    