version: "3.7"

services:
  backend-master-api-test:
    build:
      context: ./backend
      dockerfile: ./api/rest/Dockerfile
      target: builder
    environment:
      PL_DATABASE_HOST: "${PL_DATABASE_HOST:-db}"
      PL_DATABASE_NAME: "${PL_DATABASE_NAME:-pl}"
      PL_DATABASE_USER: "${PL_DATABASE_USER:-pl}"
      PL_DATABASE_PASS: "${PL_DATABASE_PASS:-pl}"
      PL_DATABASE_PORT: "${PL_DATABASE_PORT:-5432}"
    command: [ 
      "go", 
      "test", 
      "./...", 
      "-timeout",
      "30s",
      "-v"
    ]
    networks: 
      - private  
  db:
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
