version: "3.7"

services:
  backend-master-api:
    command: [ "/root/app", "--port", "8080", "--data", "/var/piqlit", "--master" ]
    volumes:
      - type: bind
        source: ./filesys/master
        target: /var/piqlit
  backend-slave-api-1:
    image: "briand787b/piqlit-backend-api:latest"
    command: ["/root/app", "--port", "8080"]
    ports:
      - "${SLAVE_PORT_1:-8081}:8080"
    networks:
      - public
      - private
  backend-slave-api-2:
    image: "briand787b/piqlit-backend-api:latest"
    command: ["/root/app", "--port", "8080"]
    ports:
      - "${SLAVE_PORT_2:-8082}:8080"
    networks:
      - public
      - private
  db:
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes: 
  db_data: