version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Docker-Compse version
          command: docker-compose -v
      - run:
          name: Docker-Compse build
          command: docker-compose build