version: 2.1
jobs:
  build:
    docker:
      - image: docker/compose:1.25.0-rc2
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Docker-Compse build
          command: docker-compose build