FROM node:13.8

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to app folder
COPY . /app

CMD [ "npm", "run", "test" ]